using System.Collections.Generic;
using BluApi.Chef.ChefAPI;

namespace BluStation.BluSprint
{
    /// <summary>
    /// An static class containing Runtime data collections
    /// </summary>
    public static class SprintData
    {
        /* <summary>Absolute path to runtime folder </summary> */
        public static string RuntimePath = ChefConfig.Root + "\\runtime";

        /* <summary>Absolute path to runtime cookbooks (runlist) folder </summary> */
        public static string RunlistPath = RuntimePath + "\\cookbooks";

        /* <summary>Absolute path to blu_sprint cookbook</summary> */
        public static string SprintPath = "UNSET";

        /* <summary>Absolute path to Ruby Stack </summary> */
        public static string RubyStack = ChefConfig.Root + "\\runtime\\RubyStack.rb";

        /* <summary>Absolute path to compiled script (BluSprint.ps1) </summary> */
        public static string CompiledSprint = ChefConfig.Root + "\\runtime\\Sprint.ps1";

        /* <summary>Absolute path to resources module (Resources.psm1) </summary> */
        public static string CompiledResources = ChefConfig.Root + "\\runtime\\Resources.psm1";

        /* <summary>Absolute path to node_object.json </summary> */
        public static string NodeObject = ChefConfig.Root + "\\runtime\\node_object.json";

        /* <summary>A list of resources generated by compiling run_list resource files.</summary> */
        public static List<string> ResourceFileList = new List<string>();

        /* <summary>A list of attributes generated by compiling run_list attributes files.</summary> */
        public static List<string> AttributeFileList = new List<string>();

        /* <summary>Sprint run_list (recipes).</summary> */
        public static List<string> SprintRunList = new List<string>();
    }
}
